### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RafaelOliveira** [laxa88/wyngine#1]
Hi, I'm making the engine Sdg (https://github.com/RafaelOliveira/Sdg) and the code started as a fork of wyngine. Now there are people that want to use it (see here https://github.com/RafaelOliveira/Sdg/issues/9) but asked me if I could choose a license for the engine. And as the code started from the code of wyngine, I'd like to ask if would be possible for wyngine to have a license too.

I dont have much experience with licenses, but I will use the MIT license, as I'm using code from others engines that is using MIT too. Others libraries of mine (like BitmapText) will use MIT too.

**Comment by laxa88** [comment]
Hi @RafaelOliveira , thanks for the message! I've updated the readme. :)
